<a href="https://colab.research.google.com/github/codebuzer/Bioactivity-Prediction-App/blob/main/mlknn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install scikit-multilearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("toy_data_model.csv")

In [ ]:
df.head(2)

ID  AA  AT  AG  AC  TA  TT  TG  TC  GA  ...  \
0      aac(6')-Ib_2_M23634  34  33  47  41  20  24  42  31  51  ...   
1  aac(6')-Ib11_1_AY136758  33  33  40  40  18  19  43  29  50  ...   

   Metronidazole  Piperacillin+Clavulanic acid  Formaldehyde  \
0              0                             0             0   
1              0                             0             0   

   Benzylkonium Chloride  Ethidium Bromide  Chlorhexidine  \
0                      0                 0              0   
1                      0                 0              0   

   Cetylpyridinium Chloride  Hydrogen peroxide  Nalidixic acid  Temperature  
0                         0                  0               0            0  
1                         0                  0               0            0  

[2 rows x 459 columns]

In [ ]:
X = df.iloc[:,1:361]
sparse_matrix_X =X.values
sparse_matrix_X

array([[34, 33, 47, ...,  0,  0,  0],
       [33, 33, 40, ...,  0,  0,  0],
       [56, 57, 75, ...,  0,  0,  0],
       ...,
       [32, 59, 26, ...,  0,  0,  0],
       [52, 58, 27, ...,  0,  0,  0],
       [37, 47, 28, ...,  0,  0,  0]])

In [ ]:
y = df.iloc[:,361:]
sparse_matrix_y = y.values
sparse_matrix_y

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train = X.iloc[1:2500,:361]
X_train.head(3)
train_X_array = X_train.values
train_X_array

array([[ 33,  33,  40, ...,   0,   0,   0],
       [ 56,  57,  75, ...,   0,   0,   0],
       [ 70,  80,  28, ...,   0,   0,   0],
       ...,
       [ 14,  25,  30, ...,   0,   0,   0],
       [  8,  15,  18, ...,   0,   0,   0],
       [117,  95,  63, ...,   0,   0,   0]])

In [ ]:
y_train = y.iloc[1:2500,:361:]
y_train.head(3)
train_y_array = y_train.values
train_y_array

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test = X.iloc[2500:,1:361]
X_test.head(2)

AT  AG  AC   TA   TT  TG  TC  GA  GT  GG  ...  Oxazolidinone  \
2500   96  62  41   93   94  42  22  52  31  19  ...              0   
2501  129  57  47  112  116  99  55  56  64  59  ...              0   

      Polymyxin  Steroid antibacterial  Pseudomonic acid  Nitroimidazole  \
2500          0                      0                 0               0   
2501          0                      0                 0               0   

      Aldehyde  Quaternary Ammonium Compound  Quaternary Ammonium Compounds  \
2500         0                             0                              0   
2501         0                             0                              0   

      Peroxide  Heat  
2500         0     0  
2501         0     0  

[2 rows x 359 columns]

In [ ]:
#from sklearn.datasets import make_multilabel_classification


#X, y = make_multilabel_classification(sparse = True, n_labels = 98,
#return_indicator = 'sparse', allow_unlabeled = False)
from skmultilearn.adapt import MLkNN
classifier = MLkNN(k=98)
classifier.fit(train_X_array,train_y_array )
classifier.fit(sparse_matrix_X, sparse_matrix_y)
MLkNN(ignore_first_neighbours=0, k=98, s=1.0)
predictions = classifier.predict(X_test)
print(type(sparse_matrix_X))
print(type(sparse_matrix_y))


TypeError: ignored