In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [24]:
train = pd.read_csv("train.csv", index_col = 0)
test= pd.read_csv("test.csv", index_col = 0)

In [26]:
train.columns,

(Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
        'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V20', 'V21', 'V22',
        'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32',
        'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42',
        'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'agenum_random',
        'ctnum_random', 'batch_A', 'batch_B', 'batch_C', 'batch_D', 'batch_E',
        'batch_F', 'batch_G', 'batch_H', 'batch_I', 'batch_J', 'batch_K',
        'batch_L', 'batch_M', 'batch_N', 'batch_O', 'batch_P', 'batch_Q',
        'batch_R', 'batch_S', 'batch_T', 'batch_U', 'ctnum_median_status',
        'infection'],
       dtype='object'),)

In [27]:
test.columns


Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50',
       'agenum_random', 'ctnum_random', 'batch_A', 'batch_B', 'batch_C',
       'batch_E', 'batch_F', 'batch_G', 'batch_H', 'batch_I', 'batch_J',
       'batch_K', 'batch_L', 'batch_M', 'batch_N', 'batch_O', 'batch_P',
       'batch_Q', 'batch_R', 'batch_S', 'batch_T', 'batch_U',
       'ctnum_median_status', 'infection'],
      dtype='object')

In [28]:
train.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V20', 'V21', 'V22',
       'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32',
       'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42',
       'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'agenum_random',
       'ctnum_random', 'batch_A', 'batch_B', 'batch_C', 'batch_D', 'batch_E',
       'batch_F', 'batch_G', 'batch_H', 'batch_I', 'batch_J', 'batch_K',
       'batch_L', 'batch_M', 'batch_N', 'batch_O', 'batch_P', 'batch_Q',
       'batch_R', 'batch_S', 'batch_T', 'batch_U', 'ctnum_median_status',
       'infection'],
      dtype='object')

In [29]:
test = test.drop(['V19'], axis = 1)
train = train.drop(['batch_D'], axis = 1)

In [30]:
X_train = train.drop(['infection'], axis = 1)
y_train = train['infection']
X_test = test.drop(['infection'], axis = 1)
y_test = test['infection']

In [31]:
X_train.shape, y_train.shape,X_test.shape,y_test.shape

((652, 72), (652,), (121, 72), (121,))

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
scaler = StandardScaler()

In [34]:
X_train = scaler.fit_transform(X_train)

In [35]:
X_test = scaler.transform(X_test)

In [36]:
# PCA 
from sklearn.decomposition import PCA
pca = PCA(n_components=None)

In [37]:
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)

In [38]:
X_train_trf.shape

(652, 72)

In [40]:
from sklearn.neighbors import KNeighborsClassifier

In [41]:
knn = KNeighborsClassifier()

In [42]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [43]:
import time
start = time.time()
y_pred = knn.predict(X_test)
print(time.time() - start)

0.07652902603149414


In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9090909090909091

In [45]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [46]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [47]:
# PCA 
from sklearn.decomposition import PCA
pca = PCA(n_components=40)

In [48]:
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)

In [49]:
X_train_trf.shape

(652, 40)

In [50]:
knn = KNeighborsClassifier()

In [51]:
knn.fit(X_train_trf,y_train)

KNeighborsClassifier()

In [52]:
y_pred = knn.predict(X_test_trf)

In [53]:
accuracy_score(y_test,y_pred)

0.9338842975206612

In [56]:
for i in range(1,72):
    pca = PCA(n_components=i)
    X_train_trf = pca.fit_transform(X_train)
    X_test_trf = pca.transform(X_test)
    
    knn = KNeighborsClassifier()
    
    knn.fit(X_train_trf,y_train)
    
    y_pred = knn.predict(X_test_trf)
    
    print((accuracy_score(y_test,y_pred))*100)
    

65.28925619834712
80.99173553719008
83.47107438016529
77.68595041322314
78.51239669421489
80.99173553719008
82.64462809917356
84.29752066115702
83.47107438016529
85.12396694214877
85.9504132231405
85.9504132231405
83.47107438016529
85.12396694214877
85.9504132231405
83.47107438016529
86.77685950413223
86.77685950413223
90.9090909090909
90.9090909090909
91.73553719008265
92.56198347107438
94.21487603305785
92.56198347107438
92.56198347107438
92.56198347107438
92.56198347107438
94.21487603305785
92.56198347107438
93.38842975206612
93.38842975206612
91.73553719008265
92.56198347107438
92.56198347107438
94.21487603305785
94.21487603305785
93.38842975206612
93.38842975206612
93.38842975206612
93.38842975206612
93.38842975206612
93.38842975206612
93.38842975206612
93.38842975206612
93.38842975206612
93.38842975206612
93.38842975206612
92.56198347107438
93.38842975206612
93.38842975206612
93.38842975206612
92.56198347107438
90.9090909090909
92.56198347107438
92.56198347107438
91.7355371900826

In [57]:
# transforming to a 2D coordinate system
pca = PCA(n_components=2)
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)

In [58]:
X_train_trf

array([[-0.76596471, -2.00564429],
       [ 1.46102019,  3.02702728],
       [ 2.24425366,  0.03686951],
       ...,
       [-4.24568802,  0.71227793],
       [ 0.11608827,  0.13413318],
       [ 2.55455559,  2.44348819]])

In [62]:
import plotly.express as px
y_train_trf = y_train.astype(str)
fig = px.scatter(x=X_train_trf[:,0],
                 y=X_train_trf[:,1],
                 color=y_train_trf,
                 color_discrete_sequence=px.colors.qualitative.G10
                )
fig.show()

In [63]:
# transforming in 3D
pca = PCA(n_components=3)
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)

In [64]:
X_train_trf

array([[-0.76596471, -2.00564443, -0.44791768],
       [ 1.46102019,  3.02702717, -3.73462091],
       [ 2.24425366,  0.03686942,  7.1577357 ],
       ...,
       [-4.24568802,  0.71227782, -2.55288058],
       [ 0.11608827,  0.13413336,  1.00991667],
       [ 2.55455559,  2.4434882 ,  3.99135747]])

In [73]:
import plotly.express as px
y_train_trf = y_train.astype(str)
fig = px.scatter_3d(train, x=X_train_trf[:,0], y=X_train_trf[:,1], z=X_train_trf[:,2],
              color=y_train_trf)
fig.update_layout(
    margin=dict(l=20, r=20, t=20, b=20),
    paper_bgcolor="LightSteelBlue",
)
fig.show()

In [67]:
pca.explained_variance_
# Eigen values

array([18.35651492,  9.5840929 ,  7.22719328])

In [78]:
train.iloc[:,0]

0     -0.330218
1      0.426675
2     -0.449942
3     -0.385247
4      0.008941
         ...   
647   -0.161713
648   -0.296854
649    0.115255
650   -0.082016
651   -0.078275
Name: V1, Length: 652, dtype: float64